version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySQL!234
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitoring

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1 # phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8085:80"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - monitoring

volumes:
  db:
    driver: local

networks:
  monitoring:
    driver: bridge
